package define

// DEFINE RESULT
const (
	OK                      = "OK"
	SUCCESS                 = "SUCCESS"
	NO_EXIST_TOKEN          = "NO_EXIST_TOKEN"
	INCORRECT_HTTP_METHOD   = "INCORRECT_HTTP_METHOD"
	NO_PARAMETER            = "NO_PARAMETER"
	TYPE_MISMATCH           = "TYPE_MISMATCH"
	CONTENT_TYPE_MISMATCH   = "CONTENT_TYPE_MISMATCH"
	NO_EXIST_CONTENT_TYPE   = "NO_EXIST_CONTENT_TYPE"
	NO_DEFINE               = "NO_DEFINE"
	NONE                    = "NONE"
	ERROR                   = "ERROR"
	DB_ERROR_ORM            = "DB_ERROR_ORM"
	DB_ERROR_REDIS          = "DB_ERROR_REDIS"
	SYSTEM_ERROR            = "SYSTEM_ERROR"
	JSON_SYNTAX_ERROR       = "JSON_SYNTAX_ERROR"
	FILE_UPLOAD_ERROR       = "FILE_UPLOAD_ERROR"
	CREATE_TOKEN_ERROR      = "CREATE_TOKEN_ERROR"
	NO_TOKEN                = "NO_TOKEN"
	INVALID_TOKEN           = "INVALID_TOKEN"
	EXPIRED_TOKEN           = "EXPIRED_TOKEN"
	ALREADY_EXISTS_NICKNAME = "ALREADY_EXISTS_NICKNAME"
	ALREADY_EXISTS_TITLE    = "ALREADY_EXISTS_TITLE"
	ALREADY_EXISTS_EMAIL    = "ALREADY_EXISTS_EMAIL"
	BLANK_VALUE             = "BLANK_VALUE"
	NO_PROGRESS             = "NO_PROGRESS"
	LOWER                   = "LOWER"
	REQUIRE_OVER_1          = "REQUIRE_OVER_1"
	NO_EXIST_DATA           = "NO_EXIST_DATA"
	NOT_AUTHOR              = "NOT_AUTHOR"
	SELF_SUBSCRIBE          = "SELF_SUBSCRIBE"
	NO_EXIST_NICK           = "NO_EXIST_NICK"
	OTHER_USER              = "OTHER_USER"
	INACTIVE_KEYWORD        = "INACTIVE_KEYWORD"
	NO_EXIST_USER           = "NO_EXIST_USER"
	CACHE_ERROR             = "CACHE_ERROR"
)

// const LIST_PER_PAGE = 2
const DATE_FORMAT_KST = "2006-02-01 15:04:05"
const MAIN_LIST_SIZE = 5

// SUCSCRIBE
const (
	FOLLOWING = "FOLLOWING"
	FOLLOWER  = "FOLLOWER"
	BOTH      = "BOTH"
)

const (
	RECENT = "RECENT"
	LIKE   = "LIKE"
)
